import { ArrowDown, ArrowUpRight, Building2, CheckCircle2, CircleDashed, Cpu, Factory, Globe2, Landmark, MapPin, Network, Ship, Sparkles, Users } from "lucide-react";

const domains = [
  ["National Highway Networks & Multi-Modal Interchanges", "High-speed road transit corridors.", Network],
  ["Urban Planning & Affordable / Rural Housing Infrastructure", "High-density smart living & regional towns.", Building2],
  ["Heavy Industry, Manufacturing & Steel / Metal Fabrication", "Industrial factory workforce.", Factory],
  ["Space Exploration & Satellite Telecommunications", "ISRO payloads, deep-space imaging, and aerospace technology.", Sparkles],
  ["Women Empowerment, Self-Help Groups & Rural Livelihoods", "Grassroots community upliftment and artisan economics.", Users],
  ["Youth, Higher Education & Entrepreneurship Ecosystems", "Gen-Z/millennial researchers and student innovators.", Landmark],
  ["Artificial Intelligence, Bionics & Deep Tech Robotics", "Advanced human-machine interfaces, hardware prototyping.", Cpu],
  ["Container Ports, Maritime Shipping & Freight Logistics", "Global supply chain integration.", Ship],
];

const assets = ["Roads", "Railways", "Airports", "Digital Infrastructure", "Ports", "Industrial Corridors"];
const schemes = ["PM Gati Shakti", "Bharatmala", "Dedicated Freight Corridor (DFC)"];
const gaps = ["Institutional Integration: Bridging policy silos across departments and tiers of government.", "Knowledge Connectivity: Closing the loop between academic R&D, labs, and market execution.", "Cross-Sector Collaboration: Uniting private enterprise, venture capital, and local communities into a central ecosystem hub."];

export default function AboutUsPage() {
  return (
    <main className="min-h-screen w-full bg-[#02050e] text-white overflow-x-hidden font-sans selection:bg-blue-500 selection:text-white">
      <section className="relative min-h-screen flex items-center overflow-hidden">
        <div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=2200&q=90" alt="Interconnected physical map of India" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-[#02050e]/75" /><div className="absolute inset-0 bg-gradient-to-r from-[#02050e] via-[#02050e]/75 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-[#02050e] via-transparent to-[#02050e]/40" /></div>
        <div className="relative z-10 max-w-7xl mx-auto w-full px-6 md:px-10 pt-28"><div className="max-w-5xl"><div className="flex items-center gap-3 mb-8"><span className="w-8 h-px bg-blue-400" /><span className="text-[10px] text-blue-300 tracking-[0.35em] uppercase">Vision, Thesis & The Integration Gap</span></div><h1 className="text-5xl sm:text-6xl md:text-8xl lg:text-[110px] font-light tracking-[-0.05em] leading-[0.88]">Every Challenge<br /><span className="text-white/90 font-thin">Leads to the</span><br /><span className="text-slate-400">Same Question.</span></h1><p className="mt-9 max-w-2xl text-lg md:text-xl text-slate-300/80 leading-8 font-light italic">&quot;How can India strengthen collaboration across governments, industries, academia, investors, research institutions and communities to accelerate national progress?&quot;</p><a href="#thesis" className="mt-10 group inline-flex items-center gap-3 px-5 py-3 border border-white/20 rounded-full bg-white/[0.03] backdrop-blur-md hover:bg-white/10 transition-all"><span className="text-[10px] uppercase tracking-[0.2em]">Explore the thesis</span><ArrowDown className="w-3.5 h-3.5 group-hover:translate-y-1 transition-transform" /></a></div></div><div className="absolute bottom-8 left-6 md:left-10 text-[9px] tracking-[0.3em] uppercase text-slate-500">Scroll to explore</div>
      </section>

      <section id="thesis" className="relative py-32 md:py-44 px-6 md:px-10 bg-[#061126]"><div className="max-w-7xl mx-auto grid lg:grid-cols-12 gap-12 lg:gap-20"><div className="lg:col-span-5"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">01 — Organizational Thesis</div><h2 className="text-4xl md:text-6xl font-light tracking-tight leading-tight">Perhaps the answer<br /><span className="text-slate-500">is already here.</span></h2><p className="mt-10 text-lg md:text-xl text-slate-300 leading-8 font-light italic">&quot;Perhaps the answer lies not in building more institutions, but in connecting the ones that already exist.&quot;</p></div><div className="lg:col-span-7"><div className="relative min-h-[420px] rounded-[32px] overflow-hidden border border-white/10"><img src="https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?auto=format&fit=crop&w=1800&q=90" alt="Connected geography and satellite infrastructure" className="absolute inset-0 w-full h-full object-cover opacity-55" /><div className="absolute inset-0 bg-gradient-to-t from-[#02050e] via-[#02050e]/30 to-transparent" /><div className="absolute bottom-8 left-8 right-8"><div className="text-[9px] text-blue-300 uppercase tracking-[0.25em] mb-4">Strategic Geographic Hubs</div><div className="flex flex-wrap gap-3">{["Delhi", "Mumbai", "Bengaluru", "Chennai"].map((hub) => <span key={hub} className="flex items-center gap-2 px-3 py-2 border border-white/15 bg-black/30 backdrop-blur-md text-xs text-white"><MapPin className="w-3.5 h-3.5 text-blue-400" />{hub}</span>)}</div><p className="mt-5 text-xs text-slate-300 leading-6">Connected via high-speed transit, green energy grids, aerospace/space launch corridors, and maritime logistics.</p></div></div></div></div></section>

      <section className="relative py-32 md:py-44 px-6 md:px-10 bg-[#02050e]"><div className="max-w-7xl mx-auto"><div className="max-w-3xl mb-16"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">02 — The Multi-Sector Integrated Circle</div><h2 className="text-4xl md:text-6xl font-light tracking-tight leading-tight">Comprehensive<br /><span className="text-slate-500">Ecosystem Coverage.</span></h2><p className="mt-7 max-w-xl text-sm text-slate-400 leading-7">Interlocking 8 key national domains into one central mission.</p></div><div className="grid md:grid-cols-2 lg:grid-cols-4 border-t border-white/10">{domains.map(([title, description, Icon], index) => <article key={title} className="p-7 border-b md:border-r border-white/10"><div className="flex items-center justify-between"><Icon className="w-5 h-5 text-blue-400" strokeWidth={1.2} /><span className="text-[9px] text-slate-600 font-mono">0{index + 1}</span></div><h3 className="mt-14 text-lg font-light text-slate-200">{title}</h3><p className="mt-3 text-xs leading-6 text-slate-500">{description}</p></article>)}</div></div></section>

      <section id="integration-gap" className="relative py-32 md:py-44 px-6 md:px-10 bg-[#061126]"><div className="max-w-7xl mx-auto"><div className="grid lg:grid-cols-12 gap-12 lg:gap-20"><div className="lg:col-span-5"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">03 — Diagnostic Analysis</div><h2 className="text-4xl md:text-6xl font-light tracking-tight leading-tight">Infrastructure<br /><span className="text-slate-500">Without Integration.</span></h2><p className="mt-9 text-sm md:text-base text-slate-400 leading-8 font-light">India has invested heavily in roads, railways, airports, industrial corridors and digital infrastructure. These investments are strengthening the country&apos;s economic foundation. The next challenge is ensuring that infrastructure enables stronger collaboration between governments, industries, universities, researchers, entrepreneurs and communities, creating ecosystems rather than isolated assets.</p></div><div className="lg:col-span-7"><div className="grid grid-cols-3 border-y border-white/10 mb-10">{[["₹12 Lakh Crore+", "Union Budget 2026 allocation for infrastructure"], ["68,000+ km", "Railway network"], ["1.46 lakh km", "National highways"]].map(([value, label]) => <div key={value} className="p-5 border-r border-white/10 last:border-r-0"><div className="text-xl md:text-2xl font-light">{value}</div><div className="mt-2 text-[9px] uppercase tracking-[0.12em] text-slate-500">{label}</div></div>)}</div><div className="grid md:grid-cols-2 gap-8"><div><div className="text-[9px] uppercase tracking-[0.2em] text-blue-400 mb-5">Existing Infrastructure</div><div className="space-y-3">{assets.map((asset) => <div key={asset} className="flex items-center gap-3 text-sm text-slate-300"><CheckCircle2 className="w-4 h-4 text-emerald-400" strokeWidth={1.2} />{asset}</div>)}</div><div className="mt-8 text-[9px] uppercase tracking-[0.2em] text-blue-400 mb-5">Government Response</div><div className="space-y-3">{schemes.map((scheme) => <div key={scheme} className="text-xs text-slate-400">{scheme}</div>)}</div></div><div><div className="text-[9px] uppercase tracking-[0.2em] text-red-300 mb-5">What&apos;s Still Missing</div><div className="space-y-5">{gaps.map((gap) => <div key={gap} className="flex gap-3 text-xs leading-6 text-slate-400"><CircleDashed className="w-4 h-4 shrink-0 text-red-300" strokeWidth={1.2} />{gap}</div>)}</div></div></div><p className="mt-10 pt-6 border-t border-white/10 text-[9px] uppercase tracking-[0.12em] text-slate-500">Data Sources: Ministry of Finance, PM Gati Shakti</p></div></div></div></section>
    </main>
  );
}
