import { ArrowDown, ArrowUpRight, Building2, Cpu, Factory, Globe2, HandCoins, Leaf, Lightbulb, Network, Rocket, ShieldCheck, Sparkles, Users, Waves, Wind } from "lucide-react";
import { useState } from "react";

const geographies = [
  ["Karnataka", "High-tech, IT, software, biotech, space tech."],
  ["Kerala", "Healthtech, sustainable tourism, spice/agri tech, deep water logistics."],
  ["Tamil Nadu", "Automotive manufacturing, hardware, renewable components, textiles."],
  ["Gujarat", "Petrochemicals, solar manufacturing, industrial commerce, diamond/trade."],
  ["Maharashtra", "Financial capital, BFSI, entertainment, heavy industrial logistics."],
  ["North East India", "Bio-resources, organic agriculture, ecotourism, cross-border trade."],
];
const industries = ["AI Innovation Campus", "Data Centers", "Modern Healthcare Campus & Research Hospital", "Precision Farming", "Industry 4.0 Manufacturing Facility", "Water Management Infrastructure", "Renewable Energy Zone", "Tourism Destination & Premium Hospitality"];
const causes = ["Women Entrepreneurship", "Youth Innovation & Infrastructure", "Rural Development", "Tribal Communities", "Accessibility & Inclusion", "Environmental Sustainability"];
const typologies = [["Startup Park", "Physical hub. Community. Workspaces."], ["Startup Café", "Casual space. First contact. Mentors."], ["Incubator Café", "Operational support. Early execution."], ["Investor Café", "HNI / angel access. Deal flow rooms."], ["Museums", "Heritage, industry, regional craft."], ["Robotics Hub", "Hardware. Manufacturing. Talent."], ["Education City", "Residencies. Schools. Research."], ["Quantum City", "Frontier. Country-grade compute."]];
const roadmap = [["Stage 1 (2026)", "Inception, initial studio seeding, Mobility lead allocation."], ["Stage 2 (2027)", "Healthcare and Med-Tech studio deployment."], ["Stage 3 (2028)", "Agritech infrastructure scaling."], ["Stage 4 (2029)", "Robotics, hardware engineering, and industrial automation."], ["Stage 5 (2030)", "Integrated Logistics, multi-modal supply chains, and sovereign exits."]];
const energySystems = ["Coastal & Offshore Wind Turbine Farms", "Mega-scale Solar Photovoltaic Arrays", "Hydroelectric Dams & Pumped Hydro Storage", "High-Voltage Smart Transmission Grids", "Green Hydrogen & Ammonia Chemical Generation Units", "Integrated Smart Industrial Eco-parks"];

function DetailList({ title, items }) {
  return <div><div className="text-[9px] uppercase tracking-[0.2em] text-blue-400 mb-5">{title}</div><div className="space-y-3">{items.map((item, index) => <div key={Array.isArray(item) ? item[0] : item} className="flex gap-3 text-sm text-slate-300"><span className="text-[9px] text-slate-600 font-mono">{String(index + 1).padStart(2, "0")}</span><span>{Array.isArray(item) ? <><strong className="font-normal text-white">{item[0]}</strong><span className="block mt-1 text-xs text-slate-500">{item[1]}</span></> : item}</span></div>)}</div></div>;
}

export default function ServicesPage() {
  const [activeStage, setActiveStage] = useState(0);
  return <main className="min-h-screen w-full bg-[#02050e] text-white overflow-x-hidden font-sans selection:bg-blue-500 selection:text-white">
    <section className="relative min-h-screen flex items-center overflow-hidden"><div className="absolute inset-0"><img src="https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=2200&q=90" alt="Connected innovation infrastructure" className="absolute inset-0 w-full h-full object-cover" /><div className="absolute inset-0 bg-[#02050e]/75" /><div className="absolute inset-0 bg-gradient-to-r from-[#02050e] via-[#02050e]/75 to-transparent" /><div className="absolute inset-0 bg-gradient-to-t from-[#02050e] via-transparent to-[#02050e]/40" /></div><div className="relative z-10 max-w-7xl mx-auto w-full px-6 md:px-10 pt-28"><div className="max-w-5xl"><div className="flex items-center gap-3 mb-8"><span className="w-8 h-px bg-blue-400" /><span className="text-[10px] text-blue-300 tracking-[0.35em] uppercase">Services & Offerings</span></div><h1 className="text-5xl sm:text-6xl md:text-8xl lg:text-[110px] font-light tracking-[-0.05em] leading-[0.88]">Building Ecosystems,<br /><span className="text-white/90 font-thin">State</span> by <span className="text-slate-400">State.</span></h1><p className="mt-9 max-w-2xl text-sm md:text-base leading-8 text-slate-300/80 font-light">Every state has different industries, institutions, talent pools and development priorities. WOI India establishes Venture Studios that identify opportunities, strengthen local ecosystems and enable collaboration.</p><a href="#studios" className="mt-10 group inline-flex items-center gap-3 px-5 py-3 border border-white/20 rounded-full bg-white/[0.03] backdrop-blur-md hover:bg-white/10 transition-all"><span className="text-[10px] uppercase tracking-[0.2em]">Explore the pillars</span><ArrowDown className="w-3.5 h-3.5 group-hover:translate-y-1 transition-transform" /></a></div></div><div className="absolute bottom-8 left-6 md:left-10 text-[9px] tracking-[0.3em] uppercase text-slate-500">Scroll to explore</div></section>

    <section id="studios" className="relative py-32 md:py-44 px-6 md:px-10 bg-[#061126]"><div className="max-w-7xl mx-auto"><div className="max-w-3xl mb-16"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">Pillar 01 • Venture Studios</div><h2 className="text-4xl md:text-6xl font-light tracking-tight leading-tight">Building ecosystems,<br /><span className="text-slate-500">state by state.</span></h2><p className="mt-8 text-sm md:text-base text-slate-400 leading-8">Together, these Venture Studios become the foundation of a nationally connected innovation network.</p><div className="mt-7 text-lg italic text-white">&quot;Every state. Every sector. Every cause.&quot;</div></div><div className="grid lg:grid-cols-3 gap-8"><DetailList title="Geography • State-Specific Hubs" items={geographies} /><DetailList title="Industry Verticals" items={industries} /><DetailList title="Causes & Social Impact Networks" items={causes} /></div></div></section>

    <section id="infrastructure" className="relative py-32 md:py-44 px-6 md:px-10 bg-[#02050e]"><div className="max-w-7xl mx-auto"><div className="max-w-3xl mb-16"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">§4 • Pillar 02 • Infrastructure</div><h2 className="text-4xl md:text-6xl font-light tracking-tight leading-tight">Physical and digital homes<br /><span className="text-slate-500">for every founder journey.</span></h2><p className="mt-8 text-sm md:text-base text-slate-400 leading-8 italic">&quot;From a corner café where a founder meets their first mentor to an entire city designed around industry needs — one architecture for India&apos;s entrepreneurship geography.&quot;</p><p className="mt-5 text-sm text-slate-500 leading-7">Three lenses. One studio. Overlapping paths — so a founder can be in tech, in a state, and in a cause, all at once. Each typology is a layer. Together, they form the country&apos;s first full-stack innovation infrastructure.</p></div><div className="grid sm:grid-cols-2 lg:grid-cols-4 border-t border-white/10">{typologies.map(([name, description], index) => <div key={name} className="p-7 border-b border-r border-white/10"><div className="flex justify-between text-[9px] font-mono text-slate-600"><span>0{index + 1}</span><Network className="w-4 h-4 text-blue-400" strokeWidth={1.2} /></div><h3 className="mt-14 text-xl font-light text-white">{name}</h3><p className="mt-3 text-xs text-slate-500 leading-6">{description}</p></div>)}</div><div className="mt-16 grid grid-cols-2 md:grid-cols-4 border-y border-white/10">{[["1.5L+ sq ft", "Startup Park • Already Live"], ["50", "Innovation Cities target"], ["10+", "Centres of Excellence"], ["100K+", "Founders activated"]].map(([value, label]) => <div key={value} className="p-6 border-r border-white/10 last:border-r-0"><div className="text-2xl md:text-4xl font-thin">{value}</div><div className="mt-2 text-[9px] uppercase tracking-[0.12em] text-slate-500">{label}</div></div>)}</div></div></section>

    <section id="capital" className="relative py-32 md:py-44 px-6 md:px-10 bg-[#061126]"><div className="max-w-7xl mx-auto grid lg:grid-cols-12 gap-12 lg:gap-20"><div className="lg:col-span-5"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">§5 • Pillars 03 & 04 • Education & Capital / WOI India Vision</div><h2 className="text-4xl md:text-6xl font-light tracking-tight">₹10,000 Cr<br /><span className="text-slate-500">Capital Fund.</span></h2><p className="mt-4 text-lg text-slate-300">Fueling the Studios</p><p className="mt-8 text-sm text-slate-400 leading-8">A dedicated capital stack designed to back <strong className="font-normal text-white">Venture Studio-originated startups</strong> from inception to scale. Capital flows directly into studio-backed ventures, ensuring aligned incentives across the entire ecosystem.</p><div className="mt-8 p-6 border border-blue-400/20 bg-blue-500/[0.04]"><div className="flex gap-3 text-white"><Lightbulb className="w-4 h-4 text-blue-400" />The fund is purpose-built to remove the #1 barrier founders face: access to early-stage capital.</div></div></div><div className="lg:col-span-7"><div className="text-[9px] uppercase tracking-[0.2em] text-blue-400 mb-5">5 Core Focus Sectors</div><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{[["Mobility", "Largest capital allocation"], ["Health", "Med-tech, healthcare delivery, biotech"], ["Agri", "Precision agriculture, supply chain efficiency"], ["Robotics", "Hardware automation, industrial bionics"], ["Logistics", "Freight tech, warehousing, cold chains"]].map(([title, description], index) => <div key={title} className="p-5 border border-white/10 bg-[#02050e]/50 min-h-32"><span className="text-[9px] font-mono text-slate-600">SECTOR_0{index + 1}</span><h3 className="mt-8 text-sm font-light text-white">{title}</h3><p className="mt-2 text-[10px] text-slate-500 leading-5">{description}</p></div>)}</div><div className="mt-12 text-[9px] uppercase tracking-[0.2em] text-blue-400 mb-5">Capital Deployment Roadmap • 2026–2030</div><div className="border-t border-white/10">{roadmap.map(([stage, description], index) => <div key={stage} className="py-5 border-b border-white/10 flex gap-5"><span className="text-sm font-mono text-blue-400">0{index + 1}</span><div><h3 className="text-sm text-white font-light">{stage}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div></div>)}</div></div></div></section>

    <section id="energy" className="relative py-32 md:py-44 px-6 md:px-10 bg-[#02050e]"><div className="max-w-7xl mx-auto grid lg:grid-cols-12 gap-12 lg:gap-20"><div className="lg:col-span-5"><div className="text-[9px] text-blue-400 tracking-[0.3em] uppercase mb-5">Reimagining Energy</div><h2 className="text-4xl md:text-6xl font-light tracking-tight">Powering the<br /><span className="text-slate-500">Next India.</span></h2><p className="mt-8 text-sm text-slate-400 leading-8">Energy has always powered economic progress. Today, it is also shaping competitiveness, industrial growth and national resilience. India has already emerged as one of the world&apos;s fastest growing renewable energy markets.</p><p className="mt-5 text-sm text-slate-400 leading-8">The next decade presents a far greater opportunity: <strong className="font-normal text-white">to build an integrated clean energy ecosystem that combines renewable generation, intelligent infrastructure, advanced storage, domestic manufacturing and emerging technologies.</strong></p><p className="mt-8 text-lg italic text-white">&quot;The future will belong to nations that don&apos;t just generate clean energy, but build entire economies around it.&quot;</p></div><div className="lg:col-span-7"><div className="relative min-h-[420px] rounded-[30px] overflow-hidden border border-white/10 mb-10"><img src="https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?auto=format&fit=crop&w=1800&q=90" alt="Renewable energy infrastructure" className="absolute inset-0 w-full h-full object-cover opacity-50" /><div className="absolute inset-0 bg-gradient-to-t from-[#02050e] via-[#02050e]/20 to-transparent" /><div className="absolute bottom-7 left-7 flex items-center gap-3 text-[9px] uppercase tracking-[0.2em] text-blue-300"><Wind className="w-4 h-4" />Clean energy leadership</div></div><div className="grid sm:grid-cols-2 gap-3">{energySystems.map((system, index) => <div key={system} className="flex items-center gap-3 p-4 border border-white/10 text-xs text-slate-300"><span className="text-[9px] font-mono text-blue-400">0{index + 1}</span>{system}</div>)}</div></div></div></section>
  </main>;
}
